<?php
    require_once('header.php');
?>

<div class="jumbotron">
    <main>
        <article>
            <h1>Erste Testseite</h1>
            <h2>HTML-Struktur ohne Backend</h2>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
            <p>HODOR</p>
        </article>
    </main>
</div>

<?php
    require_once('footer.php');
?>
