<?php
    require_once('header.php');
?>
<main role="main" class="container">
    <div class="jumbotron">
    <article>
        <h1>Erste Testseite</h1>
        <h2>HTML-Struktur ohne Backend</h2>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
        <p>HODOR</p>
    </article>
    </div>
</main>


<?php
    require_once('footer.php');
?>
